/* AUTO-GENERATED. Do not edit. */
export const tokens = {
  "shadow": {
    "none": "var(--vui-shadow-none)",
    "sm": "var(--vui-shadow-sm)",
    "md": "var(--vui-shadow-md)",
    "lg": "var(--vui-shadow-lg)"
  },
  "font": {
    "family": {
      "primary": "var(--vui-font-family-primary)"
    },
    "size": {
      "12": "var(--vui-font-size-12)",
      "14": "var(--vui-font-size-14)",
      "16": "var(--vui-font-size-16)",
      "18": "var(--vui-font-size-18)",
      "20": "var(--vui-font-size-20)",
      "24": "var(--vui-font-size-24)",
      "28": "var(--vui-font-size-28)",
      "32": "var(--vui-font-size-32)",
      "36": "var(--vui-font-size-36)",
      "40": "var(--vui-font-size-40)",
      "48": "var(--vui-font-size-48)",
      "60": "var(--vui-font-size-60)"
    },
    "weight": {
      "400": "var(--vui-font-weight-400)",
      "500": "var(--vui-font-weight-500)",
      "600": "var(--vui-font-weight-600)",
      "700": "var(--vui-font-weight-700)",
      "800": "var(--vui-font-weight-800)"
    }
  },
  "line-height": {
    "1-2": "var(--vui-line-height-1-2)",
    "1-33": "var(--vui-line-height-1-33)",
    "1-43": "var(--vui-line-height-1-43)",
    "1-5": "var(--vui-line-height-1-5)"
  },
  "border-radius": {
    "xs": "var(--vui-border-radius-xs)",
    "sm": "var(--vui-border-radius-sm)",
    "md": "var(--vui-border-radius-md)",
    "lg": "var(--vui-border-radius-lg)",
    "xl": "var(--vui-border-radius-xl)",
    "full": "var(--vui-border-radius-full)"
  },
  "space": {
    "0": "var(--vui-space-0)",
    "10": "var(--vui-space-10)",
    "20": "var(--vui-space-20)",
    "40": "var(--vui-space-40)",
    "80": "var(--vui-space-80)",
    "160": "var(--vui-space-160)",
    "240": "var(--vui-space-240)",
    "320": "var(--vui-space-320)",
    "400": "var(--vui-space-400)",
    "480": "var(--vui-space-480)",
    "640": "var(--vui-space-640)",
    "800": "var(--vui-space-800)",
    "960": "var(--vui-space-960)",
    "1280": "var(--vui-space-1280)",
    "inline-xxs": "var(--vui-space-inline-xxs)",
    "inline-xs": "var(--vui-space-inline-xs)",
    "inline-sm": "var(--vui-space-inline-sm)",
    "inline-md": "var(--vui-space-inline-md)",
    "inline-lg": "var(--vui-space-inline-lg)",
    "inline-xl": "var(--vui-space-inline-xl)",
    "inline-2xl": "var(--vui-space-inline-2xl)",
    "inline-3xl": "var(--vui-space-inline-3xl)",
    "stack-xxs": "var(--vui-space-stack-xxs)",
    "stack-xs": "var(--vui-space-stack-xs)",
    "stack-sm": "var(--vui-space-stack-sm)",
    "stack-md": "var(--vui-space-stack-md)",
    "stack-lg": "var(--vui-space-stack-lg)",
    "stack-xl": "var(--vui-space-stack-xl)",
    "stack-2xl": "var(--vui-space-stack-2xl)",
    "stack-3xl": "var(--vui-space-stack-3xl)"
  },
  "color": {
    "surface": {
      "primary": "var(--vui-surface-primary)",
      "primary-hovered": "var(--vui-surface-primary-hovered)",
      "primary-focused": "var(--vui-surface-primary-focused)",
      "primary-pressed": "var(--vui-surface-primary-pressed)",
      "primary-disabled": "var(--vui-surface-primary-disabled)",
      "primary-weak": "var(--vui-surface-primary-weak)",
      "primary-weak-hovered": "var(--vui-surface-primary-weak-hovered)",
      "primary-weak-focused": "var(--vui-surface-primary-weak-focused)",
      "primary-weak-pressed": "var(--vui-surface-primary-weak-pressed)",
      "primary-strong": "var(--vui-surface-primary-strong)",
      "primary-strong-hovered": "var(--vui-surface-primary-strong-hovered)",
      "primary-strong-focused": "var(--vui-surface-primary-strong-focused)",
      "primary-strong-pressed": "var(--vui-surface-primary-strong-pressed)",
      "secondary": "var(--vui-surface-secondary)",
      "secondary-hovered": "var(--vui-surface-secondary-hovered)",
      "secondary-focused": "var(--vui-surface-secondary-focused)",
      "secondary-pressed": "var(--vui-surface-secondary-pressed)",
      "secondary-disabled": "var(--vui-surface-secondary-disabled)",
      "secondary-weak-focused": "var(--vui-surface-secondary-weak-focused)",
      "secondary-weak-hovered": "var(--vui-surface-secondary-weak-hovered)",
      "secondary-weak": "var(--vui-surface-secondary-weak)",
      "secondary-weak-pressed": "var(--vui-surface-secondary-weak-pressed)",
      "secondary-strong": "var(--vui-surface-secondary-strong)",
      "secondary-strong-hovered": "var(--vui-surface-secondary-strong-hovered)",
      "secondary-strong-focused": "var(--vui-surface-secondary-strong-focused)",
      "secondary-strong-pressed": "var(--vui-surface-secondary-strong-pressed)",
      "neutral": "var(--vui-surface-neutral)",
      "neutral-hovered": "var(--vui-surface-neutral-hovered)",
      "neutral-focused": "var(--vui-surface-neutral-focused)",
      "neutral-pressed": "var(--vui-surface-neutral-pressed)",
      "neutral-disabled": "var(--vui-surface-neutral-disabled)",
      "neutral-weak": "var(--vui-surface-neutral-weak)",
      "neutral-weak-hovered": "var(--vui-surface-neutral-weak-hovered)",
      "neutral-weak-focused": "var(--vui-surface-neutral-weak-focused)",
      "neutral-weak-pressed": "var(--vui-surface-neutral-weak-pressed)",
      "neutral-strong": "var(--vui-surface-neutral-strong)",
      "neutral-strong-hovered": "var(--vui-surface-neutral-strong-hovered)",
      "neutral-strong-focused": "var(--vui-surface-neutral-strong-focused)",
      "neutral-strong-pressed": "var(--vui-surface-neutral-strong-pressed)"
    },
    "text": {
      "primary": "var(--vui-text-primary)",
      "primary-hovered": "var(--vui-text-primary-hovered)",
      "primary-focused": "var(--vui-text-primary-focused)",
      "primary-pressed": "var(--vui-text-primary-pressed)",
      "primary-disabled": "var(--vui-text-primary-disabled)",
      "primary-weak": "var(--vui-text-primary-weak)",
      "primary-weak-hovered": "var(--vui-text-primary-weak-hovered)",
      "primary-weak-focused": "var(--vui-text-primary-weak-focused)",
      "primary-weak-pressed": "var(--vui-text-primary-weak-pressed)",
      "primary-strong": "var(--vui-text-primary-strong)",
      "secondary": "var(--vui-text-secondary)",
      "secondary-hovered": "var(--vui-text-secondary-hovered)",
      "secondary-focused": "var(--vui-text-secondary-focused)",
      "secondary-pressed": "var(--vui-text-secondary-pressed)",
      "secondary-disabled": "var(--vui-text-secondary-disabled)",
      "secondary-weak": "var(--vui-text-secondary-weak)",
      "secondary-weak-hovered": "var(--vui-text-secondary-weak-hovered)",
      "secondary-weak-focused": "var(--vui-text-secondary-weak-focused)",
      "secondary-weak-pressed": "var(--vui-text-secondary-weak-pressed)",
      "secondary-strong": "var(--vui-text-secondary-strong)",
      "neutral": "var(--vui-text-neutral)",
      "neutral-hovered": "var(--vui-text-neutral-hovered)",
      "neutral-focused": "var(--vui-text-neutral-focused)",
      "neutral-pressed": "var(--vui-text-neutral-pressed)",
      "neutral-disabled": "var(--vui-text-neutral-disabled)",
      "neutral-weak": "var(--vui-text-neutral-weak)",
      "neutral-weak-hovered": "var(--vui-text-neutral-weak-hovered)",
      "neutral-weak-focused": "var(--vui-text-neutral-weak-focused)",
      "neutral-weak-pressed": "var(--vui-text-neutral-weak-pressed)",
      "neutral-strong": "var(--vui-text-neutral-strong)"
    },
    "border": {
      "primary": "var(--vui-border-primary)",
      "primary-hovered": "var(--vui-border-primary-hovered)",
      "primary-focused": "var(--vui-border-primary-focused)",
      "primary-pressed": "var(--vui-border-primary-pressed)",
      "primary-weakest": "var(--vui-border-primary-weakest)",
      "primary-weak": "var(--vui-border-primary-weak)",
      "primary-weak-hovered": "var(--vui-border-primary-weak-hovered)",
      "primary-weak-focused": "var(--vui-border-primary-weak-focused)",
      "primary-weak-pressed": "var(--vui-border-primary-weak-pressed)",
      "primary-strong": "var(--vui-border-primary-strong)",
      "primary-strong-hovered": "var(--vui-border-primary-strong-hovered)",
      "primary-strong-focused": "var(--vui-border-primary-strong-focused)",
      "primary-strong-pressed": "var(--vui-border-primary-strong-pressed)",
      "secondary": "var(--vui-border-secondary)",
      "secondary-hovered": "var(--vui-border-secondary-hovered)",
      "secondary-focused": "var(--vui-border-secondary-focused)",
      "secondary-pressed": "var(--vui-border-secondary-pressed)",
      "secondary-weakest": "var(--vui-border-secondary-weakest)",
      "secondary-weak": "var(--vui-border-secondary-weak)",
      "secondary-weak-hovered": "var(--vui-border-secondary-weak-hovered)",
      "secondary-weak-focused": "var(--vui-border-secondary-weak-focused)",
      "secondary-weak-pressed": "var(--vui-border-secondary-weak-pressed)",
      "secondary-strong": "var(--vui-border-secondary-strong)",
      "secondary-strong-hovered": "var(--vui-border-secondary-strong-hovered)",
      "secondary-strong-focused": "var(--vui-border-secondary-strong-focused)",
      "secondary-strong-pressed": "var(--vui-border-secondary-strong-pressed)",
      "neutral": "var(--vui-border-neutral)",
      "neutral-hovered": "var(--vui-border-neutral-hovered)",
      "neutral-focused": "var(--vui-border-neutral-focused)",
      "neutral-pressed": "var(--vui-border-neutral-pressed)",
      "neutral-disabled": "var(--vui-border-neutral-disabled)",
      "neutral-weakest": "var(--vui-border-neutral-weakest)",
      "neutral-weak": "var(--vui-border-neutral-weak)",
      "neutral-weak-hovered": "var(--vui-border-neutral-weak-hovered)",
      "neutral-weak-focused": "var(--vui-border-neutral-weak-focused)",
      "neutral-weak-pressed": "var(--vui-border-neutral-weak-pressed)",
      "neutral-strong": "var(--vui-border-neutral-strong)",
      "neutral-strong-hovered": "var(--vui-border-neutral-strong-hovered)",
      "neutral-strong-focused": "var(--vui-border-neutral-strong-focused)",
      "neutral-strong-pressed": "var(--vui-border-neutral-strong-pressed)"
    }
  },
  "elevation": {
    "none": "var(--vui-elevation-none)",
    "raised": "var(--vui-elevation-raised)",
    "lifted": "var(--vui-elevation-lifted)",
    "floating": "var(--vui-elevation-floating)"
  },
  "heading": {
    "font-family": {
      "2xl": "var(--vui-heading-2xl-font-family)",
      "xl": "var(--vui-heading-xl-font-family)",
      "lg": "var(--vui-heading-lg-font-family)",
      "md": "var(--vui-heading-md-font-family)",
      "sm": "var(--vui-heading-sm-font-family)",
      "xs": "var(--vui-heading-xs-font-family)"
    },
    "font-size": {
      "2xl": "var(--vui-heading-2xl-font-size)",
      "xl": "var(--vui-heading-xl-font-size)",
      "lg": "var(--vui-heading-lg-font-size)",
      "md": "var(--vui-heading-md-font-size)",
      "sm": "var(--vui-heading-sm-font-size)",
      "xs": "var(--vui-heading-xs-font-size)"
    },
    "font-weight": {
      "2xl": "var(--vui-heading-2xl-font-weight)",
      "xl": "var(--vui-heading-xl-font-weight)",
      "lg": "var(--vui-heading-lg-font-weight)",
      "md": "var(--vui-heading-md-font-weight)",
      "sm": "var(--vui-heading-sm-font-weight)",
      "xs": "var(--vui-heading-xs-font-weight)"
    },
    "line-height": {
      "2xl": "var(--vui-heading-2xl-line-height)",
      "xl": "var(--vui-heading-xl-line-height)",
      "lg": "var(--vui-heading-lg-line-height)",
      "md": "var(--vui-heading-md-line-height)",
      "sm": "var(--vui-heading-sm-line-height)",
      "xs": "var(--vui-heading-xs-line-height)"
    }
  },
  "body": {
    "font-family": {
      "3xl-medium": "var(--vui-body-3xl-medium-font-family)",
      "3xl-semi-bold": "var(--vui-body-3xl-semi-bold-font-family)",
      "3xl-bold": "var(--vui-body-3xl-bold-font-family)",
      "3xl": "var(--vui-body-3xl-font-family)",
      "2xl-medium": "var(--vui-body-2xl-medium-font-family)",
      "2xl-semi-bold": "var(--vui-body-2xl-semi-bold-font-family)",
      "2xl-bold": "var(--vui-body-2xl-bold-font-family)",
      "2xl": "var(--vui-body-2xl-font-family)",
      "xl-medium": "var(--vui-body-xl-medium-font-family)",
      "xl-semi-bold": "var(--vui-body-xl-semi-bold-font-family)",
      "xl-bold": "var(--vui-body-xl-bold-font-family)",
      "xl": "var(--vui-body-xl-font-family)",
      "lg-medium": "var(--vui-body-lg-medium-font-family)",
      "lg-semi-bold": "var(--vui-body-lg-semi-bold-font-family)",
      "lg-bold": "var(--vui-body-lg-bold-font-family)",
      "lg": "var(--vui-body-lg-font-family)",
      "md-medium": "var(--vui-body-md-medium-font-family)",
      "md-semi-bold": "var(--vui-body-md-semi-bold-font-family)",
      "md-bold": "var(--vui-body-md-bold-font-family)",
      "md": "var(--vui-body-md-font-family)",
      "xs-medium": "var(--vui-body-xs-medium-font-family)",
      "xs-semi-bold": "var(--vui-body-xs-semi-bold-font-family)",
      "xs-bold": "var(--vui-body-xs-bold-font-family)",
      "xs": "var(--vui-body-xs-font-family)",
      "sm": "var(--vui-body-sm-font-family)",
      "sm-medium": "var(--vui-body-sm-medium-font-family)",
      "sm-semi-bold": "var(--vui-body-sm-semi-bold-font-family)",
      "sm-bold": "var(--vui-body-sm-bold-font-family)"
    },
    "font-size": {
      "3xl-medium": "var(--vui-body-3xl-medium-font-size)",
      "3xl-semi-bold": "var(--vui-body-3xl-semi-bold-font-size)",
      "3xl-bold": "var(--vui-body-3xl-bold-font-size)",
      "3xl": "var(--vui-body-3xl-font-size)",
      "2xl-medium": "var(--vui-body-2xl-medium-font-size)",
      "2xl-semi-bold": "var(--vui-body-2xl-semi-bold-font-size)",
      "2xl-bold": "var(--vui-body-2xl-bold-font-size)",
      "2xl": "var(--vui-body-2xl-font-size)",
      "xl-medium": "var(--vui-body-xl-medium-font-size)",
      "xl-semi-bold": "var(--vui-body-xl-semi-bold-font-size)",
      "xl-bold": "var(--vui-body-xl-bold-font-size)",
      "xl": "var(--vui-body-xl-font-size)",
      "lg-medium": "var(--vui-body-lg-medium-font-size)",
      "lg-semi-bold": "var(--vui-body-lg-semi-bold-font-size)",
      "lg-bold": "var(--vui-body-lg-bold-font-size)",
      "lg": "var(--vui-body-lg-font-size)",
      "md-medium": "var(--vui-body-md-medium-font-size)",
      "md-semi-bold": "var(--vui-body-md-semi-bold-font-size)",
      "md-bold": "var(--vui-body-md-bold-font-size)",
      "md": "var(--vui-body-md-font-size)",
      "xs-medium": "var(--vui-body-xs-medium-font-size)",
      "xs-semi-bold": "var(--vui-body-xs-semi-bold-font-size)",
      "xs-bold": "var(--vui-body-xs-bold-font-size)",
      "xs": "var(--vui-body-xs-font-size)",
      "sm": "var(--vui-body-sm-font-size)",
      "sm-medium": "var(--vui-body-sm-medium-font-size)",
      "sm-semi-bold": "var(--vui-body-sm-semi-bold-font-size)",
      "sm-bold": "var(--vui-body-sm-bold-font-size)"
    },
    "font-weight": {
      "3xl-medium": "var(--vui-body-3xl-medium-font-weight)",
      "3xl-semi-bold": "var(--vui-body-3xl-semi-bold-font-weight)",
      "3xl-bold": "var(--vui-body-3xl-bold-font-weight)",
      "3xl": "var(--vui-body-3xl-font-weight)",
      "2xl-medium": "var(--vui-body-2xl-medium-font-weight)",
      "2xl-semi-bold": "var(--vui-body-2xl-semi-bold-font-weight)",
      "2xl-bold": "var(--vui-body-2xl-bold-font-weight)",
      "2xl": "var(--vui-body-2xl-font-weight)",
      "xl-medium": "var(--vui-body-xl-medium-font-weight)",
      "xl-semi-bold": "var(--vui-body-xl-semi-bold-font-weight)",
      "xl-bold": "var(--vui-body-xl-bold-font-weight)",
      "xl": "var(--vui-body-xl-font-weight)",
      "lg-medium": "var(--vui-body-lg-medium-font-weight)",
      "lg-semi-bold": "var(--vui-body-lg-semi-bold-font-weight)",
      "lg-bold": "var(--vui-body-lg-bold-font-weight)",
      "lg": "var(--vui-body-lg-font-weight)",
      "md-medium": "var(--vui-body-md-medium-font-weight)",
      "md-semi-bold": "var(--vui-body-md-semi-bold-font-weight)",
      "md-bold": "var(--vui-body-md-bold-font-weight)",
      "md": "var(--vui-body-md-font-weight)",
      "xs-medium": "var(--vui-body-xs-medium-font-weight)",
      "xs-semi-bold": "var(--vui-body-xs-semi-bold-font-weight)",
      "xs-bold": "var(--vui-body-xs-bold-font-weight)",
      "xs": "var(--vui-body-xs-font-weight)",
      "sm": "var(--vui-body-sm-font-weight)",
      "sm-medium": "var(--vui-body-sm-medium-font-weight)",
      "sm-semi-bold": "var(--vui-body-sm-semi-bold-font-weight)",
      "sm-bold": "var(--vui-body-sm-bold-font-weight)"
    },
    "line-height": {
      "3xl-medium": "var(--vui-body-3xl-medium-line-height)",
      "3xl-semi-bold": "var(--vui-body-3xl-semi-bold-line-height)",
      "3xl-bold": "var(--vui-body-3xl-bold-line-height)",
      "3xl": "var(--vui-body-3xl-line-height)",
      "2xl-medium": "var(--vui-body-2xl-medium-line-height)",
      "2xl-semi-bold": "var(--vui-body-2xl-semi-bold-line-height)",
      "2xl-bold": "var(--vui-body-2xl-bold-line-height)",
      "2xl": "var(--vui-body-2xl-line-height)",
      "xl-medium": "var(--vui-body-xl-medium-line-height)",
      "xl-semi-bold": "var(--vui-body-xl-semi-bold-line-height)",
      "xl-bold": "var(--vui-body-xl-bold-line-height)",
      "xl": "var(--vui-body-xl-line-height)",
      "lg-medium": "var(--vui-body-lg-medium-line-height)",
      "lg-semi-bold": "var(--vui-body-lg-semi-bold-line-height)",
      "lg-bold": "var(--vui-body-lg-bold-line-height)",
      "lg": "var(--vui-body-lg-line-height)",
      "md-medium": "var(--vui-body-md-medium-line-height)",
      "md-semi-bold": "var(--vui-body-md-semi-bold-line-height)",
      "md-bold": "var(--vui-body-md-bold-line-height)",
      "md": "var(--vui-body-md-line-height)",
      "xs-medium": "var(--vui-body-xs-medium-line-height)",
      "xs-semi-bold": "var(--vui-body-xs-semi-bold-line-height)",
      "xs-bold": "var(--vui-body-xs-bold-line-height)",
      "xs": "var(--vui-body-xs-line-height)",
      "sm": "var(--vui-body-sm-line-height)",
      "sm-medium": "var(--vui-body-sm-medium-line-height)",
      "sm-semi-bold": "var(--vui-body-sm-semi-bold-line-height)",
      "sm-bold": "var(--vui-body-sm-bold-line-height)"
    }
  },
  "shape": {
    "rounded-sm": "var(--vui-shape-rounded-sm)",
    "rounded-md": "var(--vui-shape-rounded-md)",
    "rounded-lg": "var(--vui-shape-rounded-lg)",
    "rounded-xl": "var(--vui-shape-rounded-xl)",
    "rounded-pill": "var(--vui-shape-rounded-pill)",
    "rounded-circle": "var(--vui-shape-rounded-circle)"
  }
} as const;
export type ShadowToken = 'lg' | 'md' | 'none' | 'sm';
export type FontFamilyToken = 'primary';
export type FontSizeToken = '12' | '14' | '16' | '18' | '20' | '24' | '28' | '32' | '36' | '40' | '48' | '60';
export type FontWeightToken = '400' | '500' | '600' | '700' | '800';
export type FontToken = FontFamilyToken | FontSizeToken | FontWeightToken;
export type LineHeightToken = '1-2' | '1-33' | '1-43' | '1-5';
export type BorderRadiusToken = 'full' | 'lg' | 'md' | 'sm' | 'xl' | 'xs';
export type SpaceToken = '0' | '10' | '1280' | '160' | '20' | '240' | '320' | '40' | '400' | '480' | '640' | '80' | '800' | '960' | 'inline-2xl' | 'inline-3xl' | 'inline-lg' | 'inline-md' | 'inline-sm' | 'inline-xl' | 'inline-xs' | 'inline-xxs' | 'stack-2xl' | 'stack-3xl' | 'stack-lg' | 'stack-md' | 'stack-sm' | 'stack-xl' | 'stack-xs' | 'stack-xxs';
export type ColorSurfaceToken = 'neutral' | 'neutral-disabled' | 'neutral-focused' | 'neutral-hovered' | 'neutral-pressed' | 'neutral-strong' | 'neutral-strong-focused' | 'neutral-strong-hovered' | 'neutral-strong-pressed' | 'neutral-weak' | 'neutral-weak-focused' | 'neutral-weak-hovered' | 'neutral-weak-pressed' | 'primary' | 'primary-disabled' | 'primary-focused' | 'primary-hovered' | 'primary-pressed' | 'primary-strong' | 'primary-strong-focused' | 'primary-strong-hovered' | 'primary-strong-pressed' | 'primary-weak' | 'primary-weak-focused' | 'primary-weak-hovered' | 'primary-weak-pressed' | 'secondary' | 'secondary-disabled' | 'secondary-focused' | 'secondary-hovered' | 'secondary-pressed' | 'secondary-strong' | 'secondary-strong-focused' | 'secondary-strong-hovered' | 'secondary-strong-pressed' | 'secondary-weak' | 'secondary-weak-focused' | 'secondary-weak-hovered' | 'secondary-weak-pressed';
export type ColorTextToken = 'neutral' | 'neutral-disabled' | 'neutral-focused' | 'neutral-hovered' | 'neutral-pressed' | 'neutral-strong' | 'neutral-weak' | 'neutral-weak-focused' | 'neutral-weak-hovered' | 'neutral-weak-pressed' | 'primary' | 'primary-disabled' | 'primary-focused' | 'primary-hovered' | 'primary-pressed' | 'primary-strong' | 'primary-weak' | 'primary-weak-focused' | 'primary-weak-hovered' | 'primary-weak-pressed' | 'secondary' | 'secondary-disabled' | 'secondary-focused' | 'secondary-hovered' | 'secondary-pressed' | 'secondary-strong' | 'secondary-weak' | 'secondary-weak-focused' | 'secondary-weak-hovered' | 'secondary-weak-pressed';
export type ColorBorderToken = 'neutral' | 'neutral-disabled' | 'neutral-focused' | 'neutral-hovered' | 'neutral-pressed' | 'neutral-strong' | 'neutral-strong-focused' | 'neutral-strong-hovered' | 'neutral-strong-pressed' | 'neutral-weak' | 'neutral-weak-focused' | 'neutral-weak-hovered' | 'neutral-weak-pressed' | 'neutral-weakest' | 'primary' | 'primary-focused' | 'primary-hovered' | 'primary-pressed' | 'primary-strong' | 'primary-strong-focused' | 'primary-strong-hovered' | 'primary-strong-pressed' | 'primary-weak' | 'primary-weak-focused' | 'primary-weak-hovered' | 'primary-weak-pressed' | 'primary-weakest' | 'secondary' | 'secondary-focused' | 'secondary-hovered' | 'secondary-pressed' | 'secondary-strong' | 'secondary-strong-focused' | 'secondary-strong-hovered' | 'secondary-strong-pressed' | 'secondary-weak' | 'secondary-weak-focused' | 'secondary-weak-hovered' | 'secondary-weak-pressed' | 'secondary-weakest';
export type ColorToken = ColorSurfaceToken | ColorTextToken | ColorBorderToken;
export type ElevationToken = 'floating' | 'lifted' | 'none' | 'raised';
export type HeadingFontFamilyToken = '2xl' | 'lg' | 'md' | 'sm' | 'xl' | 'xs';
export type HeadingFontSizeToken = '2xl' | 'lg' | 'md' | 'sm' | 'xl' | 'xs';
export type HeadingFontWeightToken = '2xl' | 'lg' | 'md' | 'sm' | 'xl' | 'xs';
export type HeadingLineHeightToken = '2xl' | 'lg' | 'md' | 'sm' | 'xl' | 'xs';
export type HeadingToken = HeadingFontFamilyToken | HeadingFontSizeToken | HeadingFontWeightToken | HeadingLineHeightToken;
export type BodyFontFamilyToken = '2xl' | '2xl-bold' | '2xl-medium' | '2xl-semi-bold' | '3xl' | '3xl-bold' | '3xl-medium' | '3xl-semi-bold' | 'lg' | 'lg-bold' | 'lg-medium' | 'lg-semi-bold' | 'md' | 'md-bold' | 'md-medium' | 'md-semi-bold' | 'sm' | 'sm-bold' | 'sm-medium' | 'sm-semi-bold' | 'xl' | 'xl-bold' | 'xl-medium' | 'xl-semi-bold' | 'xs' | 'xs-bold' | 'xs-medium' | 'xs-semi-bold';
export type BodyFontSizeToken = '2xl' | '2xl-bold' | '2xl-medium' | '2xl-semi-bold' | '3xl' | '3xl-bold' | '3xl-medium' | '3xl-semi-bold' | 'lg' | 'lg-bold' | 'lg-medium' | 'lg-semi-bold' | 'md' | 'md-bold' | 'md-medium' | 'md-semi-bold' | 'sm' | 'sm-bold' | 'sm-medium' | 'sm-semi-bold' | 'xl' | 'xl-bold' | 'xl-medium' | 'xl-semi-bold' | 'xs' | 'xs-bold' | 'xs-medium' | 'xs-semi-bold';
export type BodyFontWeightToken = '2xl' | '2xl-bold' | '2xl-medium' | '2xl-semi-bold' | '3xl' | '3xl-bold' | '3xl-medium' | '3xl-semi-bold' | 'lg' | 'lg-bold' | 'lg-medium' | 'lg-semi-bold' | 'md' | 'md-bold' | 'md-medium' | 'md-semi-bold' | 'sm' | 'sm-bold' | 'sm-medium' | 'sm-semi-bold' | 'xl' | 'xl-bold' | 'xl-medium' | 'xl-semi-bold' | 'xs' | 'xs-bold' | 'xs-medium' | 'xs-semi-bold';
export type BodyLineHeightToken = '2xl' | '2xl-bold' | '2xl-medium' | '2xl-semi-bold' | '3xl' | '3xl-bold' | '3xl-medium' | '3xl-semi-bold' | 'lg' | 'lg-bold' | 'lg-medium' | 'lg-semi-bold' | 'md' | 'md-bold' | 'md-medium' | 'md-semi-bold' | 'sm' | 'sm-bold' | 'sm-medium' | 'sm-semi-bold' | 'xl' | 'xl-bold' | 'xl-medium' | 'xl-semi-bold' | 'xs' | 'xs-bold' | 'xs-medium' | 'xs-semi-bold';
export type BodyToken = BodyFontFamilyToken | BodyFontSizeToken | BodyFontWeightToken | BodyLineHeightToken;
export type ShapeToken = 'rounded-circle' | 'rounded-lg' | 'rounded-md' | 'rounded-pill' | 'rounded-sm' | 'rounded-xl';
export const cssVar = {
  shadow: (t: keyof typeof tokens.shadow) => tokens.shadow[t],
  font: {
    family: (t: keyof typeof tokens.font.family) => tokens.font.family[t],
    size: (t: keyof typeof tokens.font.size) => tokens.font.size[t],
    weight: (t: keyof typeof tokens.font.weight) => tokens.font.weight[t],
  },
  ["line-height"]: (t: keyof typeof tokens["line-height"]) => tokens["line-height"][t],
  ["border-radius"]: (t: keyof typeof tokens["border-radius"]) => tokens["border-radius"][t],
  space: (t: keyof typeof tokens.space) => tokens.space[t],
  color: {
    surface: (t: keyof typeof tokens.color.surface) => tokens.color.surface[t],
    text: (t: keyof typeof tokens.color.text) => tokens.color.text[t],
    border: (t: keyof typeof tokens.color.border) => tokens.color.border[t],
  },
  elevation: (t: keyof typeof tokens.elevation) => tokens.elevation[t],
  heading: {
    ["font-family"]: (t: keyof typeof tokens.heading["font-family"]) => tokens.heading["font-family"][t],
    ["font-size"]: (t: keyof typeof tokens.heading["font-size"]) => tokens.heading["font-size"][t],
    ["font-weight"]: (t: keyof typeof tokens.heading["font-weight"]) => tokens.heading["font-weight"][t],
    ["line-height"]: (t: keyof typeof tokens.heading["line-height"]) => tokens.heading["line-height"][t],
  },
  body: {
    ["font-family"]: (t: keyof typeof tokens.body["font-family"]) => tokens.body["font-family"][t],
    ["font-size"]: (t: keyof typeof tokens.body["font-size"]) => tokens.body["font-size"][t],
    ["font-weight"]: (t: keyof typeof tokens.body["font-weight"]) => tokens.body["font-weight"][t],
    ["line-height"]: (t: keyof typeof tokens.body["line-height"]) => tokens.body["line-height"][t],
  },
  shape: (t: keyof typeof tokens.shape) => tokens.shape[t],
} as const;