// Auto-generated by Style Dictionary

export type BoxShadowToken =
    | "shadow-none"
    | "shadow-sm"
    | "shadow-md"
    | "shadow-lg"
    | "elevation-none"
    | "elevation-raised"
    | "elevation-lifted"
    | "elevation-floating";

export type BorderRadiusToken =
    | "border-radius-0"
    | "border-radius-1"
    | "border-radius-2"
    | "border-radius-3"
    | "border-radius-4"
    | "border-radius-5"
    | "border-radius-9999"
    | "shape-rounded-sm"
    | "shape-rounded-md"
    | "shape-rounded-lg"
    | "shape-rounded-xl"
    | "shape-rounded-pill"
    | "shape-rounded-circle";

export type SpaceToken =
    | "space-0"
    | "space-10"
    | "space-20"
    | "space-40"
    | "space-80"
    | "space-160"
    | "space-240"
    | "space-320"
    | "space-400"
    | "space-480"
    | "space-640"
    | "space-800"
    | "space-960"
    | "space-1280"
    | "space-inline-xxs"
    | "space-inline-xs"
    | "space-inline-sm"
    | "space-inline-md"
    | "space-inline-lg"
    | "space-inline-xl"
    | "space-inline-2xl"
    | "space-inline-3xl"
    | "space-stack-xxs"
    | "space-stack-xs"
    | "space-stack-sm"
    | "space-stack-md"
    | "space-stack-lg"
    | "space-stack-xl"
    | "space-stack-2xl"
    | "space-stack-3xl";
export type ColorSurfaceToken =
    | "primary"
    | "primary-hovered"
    | "primary-focused"
    | "primary-pressed"
    | "primary-disabled"
    | "primary-weak"
    | "primary-weak-hovered"
    | "primary-weak-focused"
    | "primary-weak-pressed"
    | "primary-strong"
    | "primary-strong-hovered"
    | "primary-strong-focused"
    | "primary-strong-pressed"
    | "secondary"
    | "secondary-hovered"
    | "secondary-focused"
    | "secondary-pressed"
    | "secondary-disabled"
    | "secondary-weak-focused"
    | "secondary-weak-hovered"
    | "secondary-weak"
    | "secondary-weak-pressed"
    | "secondary-strong"
    | "secondary-strong-hovered"
    | "secondary-strong-focused"
    | "secondary-strong-pressed"
    | "neutral"
    | "neutral-hovered"
    | "neutral-focused"
    | "neutral-pressed"
    | "neutral-disabled"
    | "neutral-weak"
    | "neutral-weak-hovered"
    | "neutral-weak-focused"
    | "neutral-weak-pressed"
    | "neutral-strong"
    | "neutral-strong-hovered"
    | "neutral-strong-focused"
    | "neutral-strong-pressed";

export type ColorTextToken =
    | "primary"
    | "primary-hovered"
    | "primary-focused"
    | "primary-pressed"
    | "primary-disabled"
    | "primary-weak"
    | "primary-weak-hovered"
    | "primary-weak-focused"
    | "primary-weak-pressed"
    | "primary-strong"
    | "secondary"
    | "secondary-hovered"
    | "secondary-focused"
    | "secondary-pressed"
    | "secondary-disabled"
    | "secondary-strong"
    | "secondary-weak"
    | "secondary-weak-hovered"
    | "secondary-weak-focused"
    | "secondary-weak-pressed"
    | "neutral"
    | "neutral-hovered"
    | "neutral-focused"
    | "neutral-pressed"
    | "neutral-disabled"
    | "neutral-weak"
    | "neutral-weak-hovered"
    | "neutral-weak-focused"
    | "neutral-weak-pressed"
    | "neutral-strong"
    | "neutral-strong-hovered"
    | "neutral-strong-focused"
    | "neutral-strong-pressed";

export type ColorBorderToken =
    | "primary"
    | "primary-hovered"
    | "primary-focused"
    | "primary-pressed"
    | "primary-weakest"
    | "primary-weak"
    | "primary-weak-hovered"
    | "primary-weak-focused"
    | "primary-weak-pressed"
    | "primary-strong"
    | "primary-strong-hovered"
    | "primary-strong-focused"
    | "primary-strong-pressed"
    | "secondary"
    | "secondary-hovered"
    | "secondary-focused"
    | "secondary-pressed"
    | "secondary-weakest"
    | "secondary-weak"
    | "secondary-weak-hovered"
    | "secondary-weak-focused"
    | "secondary-weak-pressed"
    | "secondary-strong"
    | "secondary-strong-hovered"
    | "secondary-strong-focused"
    | "secondary-strong-pressed"
    | "neutral"
    | "neutral-hovered"
    | "neutral-focused"
    | "neutral-pressed"
    | "neutral-disabled"
    | "neutral-weakest"
    | "neutral-weak"
    | "neutral-weak-hovered"
    | "neutral-weak-focused"
    | "neutral-weak-pressed"
    | "neutral-strong"
    | "neutral-strong-hovered"
    | "neutral-strong-focused"
    | "neutral-strong-pressed";
export type ColorToken =
    | "bittersweet-50"
    | "bittersweet-100"
    | "bittersweet-200"
    | "bittersweet-300"
    | "bittersweet-400"
    | "bittersweet-500"
    | "bittersweet-600"
    | "bittersweet-700"
    | "bittersweet-800"
    | "bittersweet-900"
    | "bittersweet-950"
    | "star-dust-0"
    | "star-dust-50"
    | "star-dust-100"
    | "star-dust-200"
    | "star-dust-300"
    | "star-dust-400"
    | "star-dust-500"
    | "star-dust-600"
    | "star-dust-700"
    | "star-dust-800"
    | "star-dust-900"
    | "star-dust-950"
    | "fern-200"
    | "fern-500"
    | "fern-800"
    | "keppel-50"
    | "keppel-100"
    | "keppel-200"
    | "keppel-300"
    | "keppel-400"
    | "keppel-500"
    | "keppel-600"
    | "keppel-700"
    | "keppel-800"
    | "keppel-900"
    | "keppel-950"
    | "carnation-200"
    | "carnation-500"
    | "carnation-800"
    | "sunglow-200"
    | "sunglow-500"
    | "sunglow-800"
    | "picton-blue-200"
    | "picton-blue-500"
    | "picton-blue-800";

export const styledSystemToTokenMappings = new Map<string, any>([
    [
        "color",
        new Map([
            [
                "surface",
                new Map([
                    ["primary", "primary-surface"],
                    ["primary-hovered", "primary-surface-hovered"],
                    ["primary-focused", "primary-surface-focused"],
                    ["primary-pressed", "primary-surface-pressed"],
                    ["primary-disabled", "primary-surface-disabled"],
                    ["primary-weak", "primary-surface-weak"],
                    ["primary-weak-hovered", "primary-surface-weak-hovered"],
                    ["primary-weak-focused", "primary-surface-weak-focused"],
                    ["primary-weak-pressed", "primary-surface-weak-pressed"],
                    ["primary-strong", "primary-surface-strong"],
                    ["primary-strong-hovered", "primary-surface-strong-hovered"],
                    ["primary-strong-focused", "primary-surface-strong-focused"],
                    ["primary-strong-pressed", "primary-surface-strong-pressed"],
                    ["secondary", "secondary-surface"],
                    ["secondary-hovered", "secondary-surface-hovered"],
                    ["secondary-focused", "secondary-surface-focused"],
                    ["secondary-pressed", "secondary-surface-pressed"],
                    ["secondary-disabled", "secondary-surface-disabled"],
                    ["secondary-weak-focused", "secondary-surface-weak-focused"],
                    ["secondary-weak-hovered", "secondary-surface-weak-hovered"],
                    ["secondary-weak", "secondary-surface-weak"],
                    ["secondary-weak-pressed", "secondary-surface-weak-pressed"],
                    ["secondary-strong", "secondary-surface-strong"],
                    ["secondary-strong-hovered", "secondary-surface-strong-hovered"],
                    ["secondary-strong-focused", "secondary-surface-strong-focused"],
                    ["secondary-strong-pressed", "secondary-surface-strong-pressed"],
                    ["neutral", "neutral-surface"],
                    ["neutral-hovered", "neutral-surface-hovered"],
                    ["neutral-focused", "neutral-surface-focused"],
                    ["neutral-pressed", "neutral-surface-pressed"],
                    ["neutral-disabled", "neutral-surface-disabled"],
                    ["neutral-weak", "neutral-surface-weak"],
                    ["neutral-weak-hovered", "neutral-surface-weak-hovered"],
                    ["neutral-weak-focused", "neutral-surface-weak-focused"],
                    ["neutral-weak-pressed", "neutral-surface-weak-pressed"],
                    ["neutral-strong", "neutral-surface-strong"],
                    ["neutral-strong-hovered", "neutral-surface-strong-hovered"],
                    ["neutral-strong-focused", "neutral-surface-strong-focused"],
                    ["neutral-strong-pressed", "neutral-surface-strong-pressed"]
                ])
            ],
            [
                "text",
                new Map([
                    ["primary", "primary-text"],
                    ["primary-hovered", "primary-text-hovered"],
                    ["primary-focused", "primary-text-focused"],
                    ["primary-pressed", "primary-text-pressed"],
                    ["primary-disabled", "primary-text-disabled"],
                    ["primary-weak", "primary-text-weak"],
                    ["primary-weak-hovered", "primary-text-weak-hovered"],
                    ["primary-weak-focused", "primary-text-weak-focused"],
                    ["primary-weak-pressed", "primary-text-weak-pressed"],
                    ["primary-strong", "primary-text-strong"],
                    ["secondary", "secondary-text"],
                    ["secondary-hovered", "secondary-text-hovered"],
                    ["secondary-focused", "secondary-text-focused"],
                    ["secondary-pressed", "secondary-text-pressed"],
                    ["secondary-disabled", "secondary-text-disabled"],
                    ["secondary-strong", "secondary-text-strong"],
                    ["secondary-weak", "secondary-text-weak"],
                    ["secondary-weak-hovered", "secondary-text-weak-hovered"],
                    ["secondary-weak-focused", "secondary-text-weak-focused"],
                    ["secondary-weak-pressed", "secondary-text-weak-pressed"],
                    ["neutral", "neutral-text"],
                    ["neutral-hovered", "neutral-text-hovered"],
                    ["neutral-focused", "neutral-text-focused"],
                    ["neutral-pressed", "neutral-text-pressed"],
                    ["neutral-disabled", "neutral-text-disabled"],
                    ["neutral-weak", "neutral-text-weak"],
                    ["neutral-weak-hovered", "neutral-text-weak-hovered"],
                    ["neutral-weak-focused", "neutral-text-weak-focused"],
                    ["neutral-weak-pressed", "neutral-text-weak-pressed"],
                    ["neutral-strong", "neutral-text-strong"],
                    ["neutral-strong-hovered", "neutral-text-strong-hovered"],
                    ["neutral-strong-focused", "neutral-text-strong-focused"],
                    ["neutral-strong-pressed", "neutral-text-strong-pressed"]
                ])
            ],
            [
                "border",
                new Map([
                    ["primary", "primary-border"],
                    ["primary-hovered", "primary-border-hovered"],
                    ["primary-focused", "primary-border-focused"],
                    ["primary-pressed", "primary-border-pressed"],
                    ["primary-weakest", "primary-border-weakest"],
                    ["primary-weak", "primary-border-weak"],
                    ["primary-weak-hovered", "primary-border-weak-hovered"],
                    ["primary-weak-focused", "primary-border-weak-focused"],
                    ["primary-weak-pressed", "primary-border-weak-pressed"],
                    ["primary-strong", "primary-border-strong"],
                    ["primary-strong-hovered", "primary-border-strong-hovered"],
                    ["primary-strong-focused", "primary-border-strong-focused"],
                    ["primary-strong-pressed", "primary-border-strong-pressed"],
                    ["secondary", "secondary-border"],
                    ["secondary-hovered", "secondary-border-hovered"],
                    ["secondary-focused", "secondary-border-focused"],
                    ["secondary-pressed", "secondary-border-pressed"],
                    ["secondary-weakest", "secondary-border-weakest"],
                    ["secondary-weak", "secondary-border-weak"],
                    ["secondary-weak-hovered", "secondary-border-weak-hovered"],
                    ["secondary-weak-focused", "secondary-border-weak-focused"],
                    ["secondary-weak-pressed", "secondary-border-weak-pressed"],
                    ["secondary-strong", "secondary-border-strong"],
                    ["secondary-strong-hovered", "secondary-border-strong-hovered"],
                    ["secondary-strong-focused", "secondary-border-strong-focused"],
                    ["secondary-strong-pressed", "secondary-border-strong-pressed"],
                    ["neutral", "neutral-border"],
                    ["neutral-hovered", "neutral-border-hovered"],
                    ["neutral-focused", "neutral-border-focused"],
                    ["neutral-pressed", "neutral-border-pressed"],
                    ["neutral-disabled", "neutral-border-disabled"],
                    ["neutral-weakest", "neutral-border-weakest"],
                    ["neutral-weak", "neutral-border-weak"],
                    ["neutral-weak-hovered", "neutral-border-weak-hovered"],
                    ["neutral-weak-focused", "neutral-border-weak-focused"],
                    ["neutral-weak-pressed", "neutral-border-weak-pressed"],
                    ["neutral-strong", "neutral-border-strong"],
                    ["neutral-strong-hovered", "neutral-border-strong-hovered"],
                    ["neutral-strong-focused", "neutral-border-strong-focused"],
                    ["neutral-strong-pressed", "neutral-border-strong-pressed"]
                ])
            ],
            [
                "core",
                new Map([
                    ["bittersweet-50", "bittersweet-50"],
                    ["bittersweet-100", "bittersweet-100"],
                    ["bittersweet-200", "bittersweet-200"],
                    ["bittersweet-300", "bittersweet-300"],
                    ["bittersweet-400", "bittersweet-400"],
                    ["bittersweet-500", "bittersweet-500"],
                    ["bittersweet-600", "bittersweet-600"],
                    ["bittersweet-700", "bittersweet-700"],
                    ["bittersweet-800", "bittersweet-800"],
                    ["bittersweet-900", "bittersweet-900"],
                    ["bittersweet-950", "bittersweet-950"],
                    ["star-dust-0", "star-dust-0"],
                    ["star-dust-50", "star-dust-50"],
                    ["star-dust-100", "star-dust-100"],
                    ["star-dust-200", "star-dust-200"],
                    ["star-dust-300", "star-dust-300"],
                    ["star-dust-400", "star-dust-400"],
                    ["star-dust-500", "star-dust-500"],
                    ["star-dust-600", "star-dust-600"],
                    ["star-dust-700", "star-dust-700"],
                    ["star-dust-800", "star-dust-800"],
                    ["star-dust-900", "star-dust-900"],
                    ["star-dust-950", "star-dust-950"],
                    ["fern-200", "fern-200"],
                    ["fern-500", "fern-500"],
                    ["fern-800", "fern-800"],
                    ["keppel-50", "keppel-50"],
                    ["keppel-100", "keppel-100"],
                    ["keppel-200", "keppel-200"],
                    ["keppel-300", "keppel-300"],
                    ["keppel-400", "keppel-400"],
                    ["keppel-500", "keppel-500"],
                    ["keppel-600", "keppel-600"],
                    ["keppel-700", "keppel-700"],
                    ["keppel-800", "keppel-800"],
                    ["keppel-900", "keppel-900"],
                    ["keppel-950", "keppel-950"],
                    ["carnation-200", "carnation-200"],
                    ["carnation-500", "carnation-500"],
                    ["carnation-800", "carnation-800"],
                    ["sunglow-200", "sunglow-200"],
                    ["sunglow-500", "sunglow-500"],
                    ["sunglow-800", "sunglow-800"],
                    ["picton-blue-200", "picton-blue-200"],
                    ["picton-blue-500", "picton-blue-500"],
                    ["picton-blue-800", "picton-blue-800"]
                ])
            ]
        ])
    ],
    [
        "boxShadow",
        new Map([
            ["shadow-none", "shadow-none"],
            ["shadow-sm", "shadow-sm"],
            ["shadow-md", "shadow-md"],
            ["shadow-lg", "shadow-lg"],
            ["elevation-none", "elevation-none"],
            ["elevation-raised", "elevation-raised"],
            ["elevation-lifted", "elevation-lifted"],
            ["elevation-floating", "elevation-floating"]
        ])
    ],
    [
        "borderRadius",
        new Map([
            ["border-radius-0", "border-radius-0"],
            ["border-radius-1", "border-radius-1"],
            ["border-radius-2", "border-radius-2"],
            ["border-radius-3", "border-radius-3"],
            ["border-radius-4", "border-radius-4"],
            ["border-radius-5", "border-radius-5"],
            ["border-radius-9999", "border-radius-9999"],
            ["shape-rounded-sm", "shape-rounded-sm"],
            ["shape-rounded-md", "shape-rounded-md"],
            ["shape-rounded-lg", "shape-rounded-lg"],
            ["shape-rounded-xl", "shape-rounded-xl"],
            ["shape-rounded-pill", "shape-rounded-pill"],
            ["shape-rounded-circle", "shape-rounded-circle"]
        ])
    ],
    [
        "space",
        new Map([
            ["space-0", "space-0"],
            ["space-10", "space-10"],
            ["space-20", "space-20"],
            ["space-40", "space-40"],
            ["space-80", "space-80"],
            ["space-160", "space-160"],
            ["space-240", "space-240"],
            ["space-320", "space-320"],
            ["space-400", "space-400"],
            ["space-480", "space-480"],
            ["space-640", "space-640"],
            ["space-800", "space-800"],
            ["space-960", "space-960"],
            ["space-1280", "space-1280"],
            ["space-inline-xxs", "space-inline-xxs"],
            ["space-inline-xs", "space-inline-xs"],
            ["space-inline-sm", "space-inline-sm"],
            ["space-inline-md", "space-inline-md"],
            ["space-inline-lg", "space-inline-lg"],
            ["space-inline-xl", "space-inline-xl"],
            ["space-inline-2xl", "space-inline-2xl"],
            ["space-inline-3xl", "space-inline-3xl"],
            ["space-stack-xxs", "space-stack-xxs"],
            ["space-stack-xs", "space-stack-xs"],
            ["space-stack-sm", "space-stack-sm"],
            ["space-stack-md", "space-stack-md"],
            ["space-stack-lg", "space-stack-lg"],
            ["space-stack-xl", "space-stack-xl"],
            ["space-stack-2xl", "space-stack-2xl"],
            ["space-stack-3xl", "space-stack-3xl"]
        ])
    ]
]);
