name: Release

on:
    push:
        branches:
            - main # Or your default branch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 8

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org/"

            - run: pnpm install

            - name: Create Release Pull Request or Publish to npm
              uses: changesets/action@v1
              with:
                  publish: pnpm changeset publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
